Update Gather.ps1
Josch62/Gather-Script-For-ConfigMgr-TS pull request #3
Opened 2024-02-28 22:40 UTC by gwblok

Adding a specific identifier used to match models during OSD for hardware specific packages.
Covers Surface, Lenovo, Dell, HP & Intel devices, using their vendor recommended matching process

2024-02-28 23:09 UTC, Josch62 commented
Can I suggest reducing the number of Get-CimInstance (50%) by doing something like this instead: 

function Get-MachineMatchID {
    $Manufacturer = (Get-CimInstance -ClassName Win32_ComputerSystem).Manufacturer
    $MachineMatchID = "Unknown"

    if ($Manufacturer -match "Dell" -or $Manufacturer -match "Microsoft"){
        $MachineMatchID = (Get-CimInstance -ClassName Win32_ComputerSystem).SystemSKUNumber
    }
    elseif ($Manufacturer -match "Lenovo"){
        $MachineMatchID = ((Get-CimInstance -Class "Win32_Bios" -Namespace "root/cimv2").SMBIOSBIOSVersion).SubString(0, 4)
    }
    
    if ($MachineMatchID -eq "Unknown"){
        $MachineMatchID = (Get-CimInstance -ClassName Win32_BaseBoard).Product
    }

    $TSvars.Add("MachineMatchID", $MachineMatchID)
}

2024-02-29 00:11 UTC, gwblok commented
Works for me!  I like it!
Thanks

On Wed, Feb 28, 2024, 5:09 PM Johan Schrewelius ***@***.***>
wrote:

> Can I suggest reducing the number of Get-CimInstance (50%) by doing
> something like this instead:
>
> function Get-MachineMatchID {
> $Manufacturer = (Get-CimInstance -ClassName
> Win32_ComputerSystem).Manufacturer
> $MachineMatchID = "Unknown"
>
> if ($Manufacturer -match "Dell" -or $Manufacturer -match "Microsoft"){
>     $MachineMatchID = (Get-CimInstance -ClassName Win32_ComputerSystem).SystemSKUNumber
> }
> elseif ($Manufacturer -match "Lenovo"){
>     $MachineMatchID = ((Get-CimInstance -Class "Win32_Bios" -Namespace "root/cimv2").SMBIOSBIOSVersion).SubString(0, 4)
> }
>
> if ($MachineMatchID -eq "Unknown"){
>     $MachineMatchID = (Get-CimInstance -ClassName Win32_BaseBoard).Product
> }
>
> $TSvars.Add("MachineMatchID", $MachineMatchID)
>
> }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Josch62/Gather-Script-For-ConfigMgr-TS/pull/3#issuecomment-1970070370>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGIX45IJ4BZTB45OGEDXDCTYVZRSHAVCNFSM6AAAAABD64CJEKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZQGA3TAMZXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-29 02:53 UTC, Josch62 requested changes
Please update to, after verifying matching functionality:

function Get-MachineMatchID {
    $Manufacturer = (Get-CimInstance -ClassName Win32_ComputerSystem).Manufacturer
    $MachineMatchID = "Unknown"

    if ($Manufacturer -match "Dell" -or $Manufacturer -match "Microsoft"){
        $MachineMatchID = (Get-CimInstance -ClassName Win32_ComputerSystem).SystemSKUNumber
    }
    elseif ($Manufacturer -match "Lenovo"){
        $MachineMatchID = ((Get-CimInstance -Class "Win32_Bios" -Namespace "root/cimv2").SMBIOSBIOSVersion).SubString(0, 4)
    }
    
    if ($MachineMatchID -eq "Unknown"){
        $MachineMatchID = (Get-CimInstance -ClassName Win32_BaseBoard).Product
    }

    $TSvars.Add("MachineMatchID", $MachineMatchID)
}

2024-02-29 03:56 UTC, gwblok commented
I'm updating my fork .. testing so far is good.
Thanks for the updated code.

2024-02-29 03:56 UTC, closed without merging